In [1]:
import pyhf
import numpy as np

In [2]:
model = pyhf.simplemodels.hepdata_like([5, 10], [50, 30], [2, 3])
data = [55, 33] + model.config.auxdata
parameters = [1.0, 1.0, 1.0]  # nominal parameters
test_poi = 1.0

In [3]:
model.logpdf(parameters, data)  # evaluate log likelihood

array([-13.60586994])

In [4]:
bestfit_pars = pyhf.infer.mle.fit(data, model)
bestfit_pars

array([0.41202114, 1.00420257, 0.99222999])

In [5]:
# we've maximized the loglikelihood (or minimized the neg. log likelihood)
model.logpdf(bestfit_pars, data)

array([-13.04446523])

In [6]:
cls = pyhf.infer.hypotest(test_poi, data, model)
cls

array(0.22800597)

In [7]:
CLs_obs, CLs_exp = pyhf.infer.hypotest(test_poi, data, model, return_expected=True)
print(f"Observed CLs: {CLs_obs:.4f}")
print(f"Expected CLs: {CLs_exp:.4f}")

Observed CLs: 0.2280
Expected CLs: 0.1025


In [8]:
CLs_obs, CLs_exp = pyhf.infer.hypotest(test_poi, data, model, return_expected_set=True)
print(f"      Observed CLs: {CLs_obs:.4f}")
for expected_value, n_sigma in zip(CLs_exp, np.arange(-2, 3)):
    print(f"Expected CLs({n_sigma:2d} σ): {expected_value:.4f}")

      Observed CLs: 0.2280
Expected CLs(-2 σ): 0.0062
Expected CLs(-1 σ): 0.0267
Expected CLs( 0 σ): 0.1025
Expected CLs( 1 σ): 0.3131
Expected CLs( 2 σ): 0.6582
